### ISSUE TITLE
The link of rrdb failed for undefined ReadOptions reference in ubuntu

### ISSUE THREAD

**Issue by lshmouse** [imzhenyu/rocksdb.replicated#1]
```
$ make 
Linking CXX executable bin/rrdb/rrdb
CMakeFiles/rrdb.dir/rrdb.server.impl.cpp.o: In function `dsn::apps::rrdb_service_impl::rrdb_service_impl(dsn::replication::replica*, std::shared_ptr<dsn::configuration>&)':
rrdb.server.impl.cpp:(.text+0x269): undefined reference to `rocksdb::ReadOptions::ReadOptions()'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/rrdb/rrdb] Error 1
make[1]: *** [CMakeFiles/rrdb.dir/all] Error 2
make: *** [all] Error 2
```

After a check, there no problem in librocksdb.so. Maybe there is a bug in the Makefile.

**Comment by lshmouse** [comment]
I found the same problem when compiling a rocksdb example. So the problem must be in rocksdb or the method of compile option. I will close this and submit a issue in rocksdb

**Comment by imzhenyu** [comment]
I see. Good luck!

Sent from my Windows Phone

---

发件人: Liu Shaohuimailto:notifications@github.com
发送时间: ‎2015/‎6/‎4 11:20
收件人: imzhenyu/rocksdb.replicatedmailto:rocksdb.replicated@noreply.github.com
主题: Re: [rocksdb.replicated] The link of rrdb failed for undefined ReadOptions reference in ubuntu (#1)

I found the same problem when compiling a rocksdb example. So the problem must be in rocksdb or the method of compile option. I will close this and submit a issue in rocksdb

---
